"""add verification columns to users

Revision ID: c7e68252e36f
Revises: 6688ce78843b
Create Date: 2026-03-17 12:37:02.214955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e68252e36f'
down_revision: Union[str, Sequence[str], None] = '6688ce78843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mobile_otp', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mobile_otp_expires', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mobile_otp_expires')
    op.drop_column('users', 'mobile_otp')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
